config/routes.rb
Rails.application.routes.draw do
# ユーザー用
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

#ゲストログイン用
devise_scope :user do
  post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
end

# 管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

scope module: :public do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get 'search' => 'searches#search'
  get '/my_page' => 'users#my_page'
  #「退会する」を押した時に本当に退会するか確認をする画面
  get 'users/confirm_deleted' => 'users#confirm_deleted', as: 'confirm_deleted'
  #退会処理
  patch 'users/is_deleted' => 'users#is_deleted', as: 'is_deleted'
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :posts do
    #favoritesの一覧ページ,いいねした投稿の一覧ページのためon: :collection使用
    get :favorites, on: :collection
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
end

namespace :admin do
  root to: 'posts#index'
  get 'search' => 'searches#search'
  resources :users, only: [:index, :show, :edit, :update]
  resources :posts, only: [:show, :destroy]
  resources :comments, only: [:destroy]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true, length: {maximum:100}
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!

  #コメント削除機能非同期化
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/_count.html.erb
コメント数：<%= post.comments.count %>

app/views/admin/comments/_index.html.erb
<div class="card-text">
  <% post.comments.each do |comment| %>
    <div class="media border rounded mb-3">
      <div class="p-3">
        <%= link_to user_path(comment.user.id) do %>
          <div><%= image_tag comment.user.get_profile_image(70,70), class: "mt-o rounded-circle"; %></div>
          <div class="text-center"><%= comment.user.name %></div>
        <% end %>
      </div>
      <div class="media-body p-3">
        <div class="row">
          <div class="col-12"><%= comment.created_at.strftime('%Y/%m/%d') %></div>
        </div>
        <div class="row">
          <div class="col-8"><%= comment.comment %></div>
          <div class="col-2"><%= link_to '削除', admin_comment_path(comment.id), method: :delete, remote: true, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/comments/destroy.js.erb
$('#comments-count').html("<%= j(render 'admin/comments/count', post: @comment.post) %>")
$('#comments-area').html("<%= j(render 'admin/comments/index', post: @comment.post) %>")