config/routes.rb
Rails.application.routes.draw do
# ユーザー用
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

#ゲストログイン用
devise_scope :user do
  post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
end

# 管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

scope module: :public do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get 'search' => 'searches#search'
  get '/my_page' => 'users#my_page'
  #「退会する」を押した時に本当に退会するか確認をする画面
  get 'users/confirm_deleted' => 'users#confirm_deleted', as: 'confirm_deleted'
  #退会処理
  patch 'users/is_deleted' => 'users#is_deleted', as: 'is_deleted'
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :posts do
    #favoritesの一覧ページ,いいねした投稿の一覧ページのためon: :collection使用
    get :favorites, on: :collection
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
end

namespace :admin do
  root to: 'posts#index'
  get 'search' => 'searches#search'
  resources :users, only: [:index, :show, :edit, :update]
  resources :posts, only: [:show, :destroy]
  resources :comments, only: [:destroy]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!

  #ユーザー名とメニュー名で曖昧検索するため
  def search
    @content = params[:content]
    @users = User.search_for(@content).page(params[:page])
    @posts = Post.search_for(@content).page(params[:page])
  end

end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/_form.html.erb
<% if admin_signed_in? %>
  <div class="search_form">
    <%= form_with url: admin_search_path, method: :get, local: true do |f| %>
      <%= f.text_field :content, class: "col-lg-4 col-md-6 col-8",  placeholder: "ユーザー名、またはメニュー名を入力", value: @content %>
      <%= f.submit '検索', class: "btn btn-sm btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/admin/searches/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3 mx-auto">
      <%= render 'layouts/admin_sidebar' %>
    </div>
    <div class="col-lg-9 mx-auto">
      <div class="card shadow-lg py-3">
        <% if @users.present? && @posts.present? %>
          <div class="px-3">
            <h3 class="headline col-lg-9 col-md-12 col-sm-12 text-center mb-3">【ユーザーとメニュー名の検索結果】検索ワード："<%= @content %>"</h3>
            <h4>【ユーザー】</h4>
              <%= render 'admin/users/index', users: @users %>
            <hr class="mt-5">
            <h4>【メニュー名】</h4>
          </div>
          <div class="col-lg-8 col-md-8 col-sm-12 mx-auto">
            <%= render 'admin/posts/index', posts: @posts %>
          </div>

        <% elsif @users.present? && @posts.empty? %>
          <div class="px-3">
            <h3 class="headline col-lg-9 col-md-12 col-sm-12 text-center mb-3">【ユーザーの検索結果】検索ワード："<%= @content %>"</h3>
            <h4>【ユーザー】</h4>
            <%= render 'admin/users/index', users: @users %>
          </div>

        <% elsif @users.empty? && @posts.present? %>
          <div class="px-3">
            <h3 class="headline col-lg-9 col-md-12 col-sm-12 text-center mb-3">【メニュー名の検索結果】検索ワード："<%= @content %>"</h3>
            <h4>【メニュー名】</h4>
          </div>
          <div class="col-lg-8 col-md-8 col-sm-12 mx-auto">
            <%= render 'admin/posts/index', posts: @posts %>
          </div>

        <% else %>
          <div class="px-3">
            <h3>"<%= @content %>"に該当はありません。</h3>
          </div>
        <% end %>
      </div>
      <%= link_to '戻る', :back, class: "btn btn-outline-dark mt-3" %>
    </div>
  </div>
</div>