config/routes.rb
Rails.application.routes.draw do
# ユーザー用
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

#ゲストログイン用
devise_scope :user do
  post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
end

# 管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

scope module: :public do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get 'search' => 'searches#search'
  get '/my_page' => 'users#my_page'
  #「退会する」を押した時に本当に退会するか確認をする画面
  get 'users/confirm_deleted' => 'users#confirm_deleted', as: 'confirm_deleted'
  #退会処理
  patch 'users/is_deleted' => 'users#is_deleted', as: 'is_deleted'
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :posts do
    #favoritesの一覧ページ,いいねした投稿の一覧ページのためon: :collection使用
    get :favorites, on: :collection
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
end

namespace :admin do
  root to: 'posts#index'
  get 'search' => 'searches#search'
  resources :users, only: [:index, :show, :edit, :update]
  resources :posts, only: [:show, :destroy]
  resources :comments, only: [:destroy]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  validates :shop_name, presence: true, length: { maximum: 30 }
  validates :menu, presence: true, length: { maximum: 30 }
  validates :impression, presence: true, length: { maximum: 100 }
  validates :price, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 9_999_999 }, format: { with: /\A[0-9]+\z/ }
  validates :volume_status, presence: true
  validates :star, presence: true

  has_one_attached :image

  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  has_many :comments, dependent: :destroy

  #物足りないなどの量感のステータスをenumで管理
  enum volume_status: { full: 0, just_right: 1, not_enough: 2 }

  ##投稿詳細画面でお店の住所の地図を表示させるため
  #ユーザーに入力してもらった住所から緯度経度をgeocorderで取得
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  #トップページを過去１週間のいいね順で投稿一覧を表示させるため
  def self.week_posts
    #(今日の日付から-6することで過去1週間の日付を取得)..(今日の日付が変わる最後の時間23:59:59を取得)
    where(created_at: ((Time.current.at_end_of_day - 1.day).at_beginning_of_day)..(Time.current.at_end_of_day))
  end

  #投稿機能に画像も投稿できるようにするため
  def get_image(width, height, shape = "rectangle")
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_post_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    #投稿履歴のみ正方形で表示するため
    if shape == "square"
      image.variant({gravity: :center, resize: "#{width}x#{height}^", crop: "#{width}x#{height}+0+0"}).processed
    else
      image.variant(resize_to_limit: [width, height]).processed
    end
  end

  #引数で渡されたユーザidがFavoritesテーブル内に存在するか確認する
  def favorited_by?(user)
    #後置修飾の"if user"は記述しないと非ログイン時にいいね機能のある画面を表示できないため記述
    favorites.exists?(user_id: user.id) if user
  end

  #メニュー名を曖昧検索するためのメソッド
  def self.search_for(content)
    if content != nil
      where('menu LIKE ?', '%' + content + '%').order(created_at: :desc)
    else
      order(created_at: :desc)
    end
  end

  ##[管理者側、ユーザー側]サイドバーにソート機能を実装
  def self.sort_index(sort)
    case (sort)
      #投稿の古い順に並び替え
      when 'old'
        order(created_at: :asc)
      #投稿の星が多い順に並び替え
      when 'star_count'
        order(star: :desc)
      #投稿のいいねが多い順に並び替え
      when 'favorite_count'
        eager_load(:favorites).group('posts.id').order('count(favorites.post_id) DESC')
      #投稿のコメントが多い順に並び替え
      when 'comment_count'
        eager_load(:comments).group('posts.id').order('count(comments.post_id) DESC')
      else
        #投稿の新しい順に並び替え
        order(created_at: :desc)
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    ##サイドバーにソート機能を実装
    #sort_indexメソッドはモデルに記述
    @posts = Post.sort_index(params[:sort]).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to admin_root_path
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_favorites-count.html.erb
<% if post.favorites.count != 0 %>
  <p><i class="fas fa-heart" style="color: #ff0000;"></i><%= post.favorites.count %></p>
<% else %>
  <p><i class="far fa-heart" style="color: #000000;"></i>0</p>
<% end %>

app/views/admin/posts/_history.html.erb
<div class="row">
  <div class="d-flex flex-wrap justify-content-evenly col-12">
    <% posts.each do |post| %>
      <div class="col-md-4 mb-3">
        <%= link_to admin_post_path(post.id) do %>
          <%= image_tag post.get_image(250,250,"square"), class: "w-100 img-thumbnail mx-1 my-1" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<div class="mt-4">
  <%= paginate posts %>
</div>

app/views/admin/posts/_index.html.erb
<div class="card-list-container mb-5">
  <% posts.each do |post| %>
    <div class="card w-70 mx-auto mb-5 shadow-lg">
      <div class="card-header">
        <span>
          <%= link_to admin_user_path(post.user.id) do %>
            <%= image_tag post.user.get_profile_image(50,50), class: "mt-o rounded-circle"; %>
          <% end %>
        </span>
        <span><%= link_to post.user.name, admin_user_path(post.user.id), class: "text-dark" %></span>
      </div>
      <%= link_to admin_post_path(post.id) do %>
        <%= image_tag post.get_image(700,700), class: "border-bottom card-img-top"; %>
      <% end %>
      <div class="card-body">
        <div class="row">
          <div class="ml-3">
            <%= render 'admin/posts/favorites-count', post: post %>
          </div>
          <div class="ml-3">
            <%= render 'admin/comments/count', post: post %>
          </div>
          <div class="ml-5">
            <b>
              <% if post.user.released? %>
                <font color="#28a745">公開</font>
              <% elsif post.user.nonreleased? %>
                <font color="#6c757d ">非公開</font>
              <% else %>
                <font color="#dc3545">退会</font>
              <% end %>
            </b>
          </div>
        </div>
        <div class="card-title">
          お店の名前：<%= link_to post.shop_name, admin_post_path(post.id), class: "text-dark" %>
        </div>
        <div class="card-text">
          メニュー名：<%= link_to post.menu, admin_post_path(post.id), class: "text-dark" %>
        </div>
        <div class="mt-2 d-flex">
          また食べたい度：<%= render "public/posts/static_rate", post: post %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= paginate posts %>

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3 mx-auto">
      <%= render 'layouts/admin_sidebar' %>
    </div>
    <div class="col-lg-9 mx-auto">
      <div class="card shadow-lg py-3">
        <div class="px-3">
          <h2 class="headline col-lg-6 col-md-7 col-sm-12 text-center">投稿一覧</h2>
        </div>
        <div class="col-lg-8 col-md-11 col-sm-12 mx-auto">
          <%= render 'index', posts: @posts %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3 mx-auto">
      <%= render 'layouts/admin_sidebar' %>
    </div>
    <div class="col-lg-9 mx-auto">
        <div class="card shadow-lg px-3 py-3">
          <!--begin:post details-->
          <h2 class="headline col-lg-4 col-md-7 col-sm-12 text-center">投稿詳細</h2>
          <div class="row">
            <div class="pl-3 mb-2">
              <%= link_to admin_user_path(@post.user.id) do %>
                <%= image_tag @post.user.get_profile_image(50,50), class: "mt-o rounded-circle"; %>
                <%= @post.user.name %>
              <% end %>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-12 col-md-7 mb-3">
              <div><%= image_tag @post.get_image(500,400), class: "img-thumbnail mx-1 my-1 shadow" %></div>
              <div><%= render 'admin/posts/favorites-count', post: @post %></div>
              <div class="text-center">
                <%= link_to "投稿を削除", admin_post_path, method: :delete, "data-confirm" => "本当に削除しますか？", class: 'btn btn-danger' %>
              </div>
            </div>
            <div class="pl-3">
              <dl>
                <dt>投稿日</dt>
                <dd class="post-detail"><%= @post.created_at.strftime('%Y/%m/%d') %></dd>
                <dt>お店の名前</dt>
                <dd class="post-detail"><%= @post.shop_name %></dd>
                <dt>住所</dt>
                <dd class="post-detail">
                  <% if @post.address.present? %>
                    <%= @post.address %>
                  <% else %>
                    住所の情報が入力されていません。
                  <% end %>
                </dd>
                <dt>メニュー名</dt>
                <dd class="post-detail"><%= @post.menu %></dd>
                <dt>感想</dt>
                <dd class="post-detail"><%= @post.impression %></dd>
                <dt>値段</dt>
                <dd class="post-detail">
                  <% if @post.price.present? %>
                    <%= @post.price.to_s(:delimited, delimiter: ',') %>円
                  <% else %>
                    値段が入力されていません。
                  <% end %>
                </dd>
                <dt>ボリューム</dt>
                <dd class="post-detail"><%= @post.volume_status_i18n %></dd>
                <dt>また食べたい度</dt>
                <dd class="post-detail"><%= render "public/posts/static_rate", post: @post %></dd>
              </dl>
            </div>
          </div>
          <!--end:post details-->
          <hr>
          <!--begin:list of comments-->
          <div class="row">
            <div class="col-12">
              <h3 class="headline col-lg-4 col-md-7 col-sm-12 text-center">コメント一覧</h3>
              <div id="comments-count">
                <%= render 'admin/comments/count', post: @post %>
              </div>
              <div id="comments-area">
                <%= render 'admin/comments/index', post: @post %>
              </div>
            </div>
          </div>
          <!--end:list of comments-->
          <hr>
          <!--begin:map display-->
          <div class="row">
            <div class="col-12">
              <h3 class="headline col-lg-4 col-md-7 col-sm-12 text-center">マップ</h3>
            </div>
            <div class="col-12">
              <% if @post.address.present? %>
                <div id="map"></div>
                <style>
                  #map {
                    height: 500px;
                    width: 100%;
                  }
                </style>
                <script>
                  function initMap() {
                    var shop = {lat: <%= @post.latitude %>, lng: <%= @post.longitude %>};
                    var map = new google.maps.Map(document.getElementById('map'), {
                      zoom: 16,
                      center: shop
                    });
                    var transitLayer = new google.maps.TransitLayer();
                    transitLayer.setMap(map);

                    var contentString = '住所：<%= @post.address %>';
                    var infowindow = new google.maps.InfoWindow({
                      content: contentString
                    });
                    var marker = new google.maps.Marker({
                      position: shop,
                      map: map
                    });
                       }
                </script>
                <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLEMAP'] %>&callback=initMap"async defer></script>
              <% else %>
                住所の情報が入力されていません。
              <% end %>
            </div>
          </div>
          <!--end:map display-->
        </div>
      <%= link_to '戻る', :back, class: "btn btn-outline-dark mt-3" %>
    </div>
  </div>
</div>