config/routes.rb
Rails.application.routes.draw do
# ユーザー用
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

#ゲストログイン用
devise_scope :user do
  post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
end

# 管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

scope module: :public do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get 'search' => 'searches#search'
  get '/my_page' => 'users#my_page'
  #「退会する」を押した時に本当に退会するか確認をする画面
  get 'users/confirm_deleted' => 'users#confirm_deleted', as: 'confirm_deleted'
  #退会処理
  patch 'users/is_deleted' => 'users#is_deleted', as: 'is_deleted'
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :posts do
    #favoritesの一覧ページ,いいねした投稿の一覧ページのためon: :collection使用
    get :favorites, on: :collection
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
end

namespace :admin do
  root to: 'posts#index'
  get 'search' => 'searches#search'
  resources :users, only: [:index, :show, :edit, :update]
  resources :posts, only: [:show, :destroy]
  resources :comments, only: [:destroy]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_sidebar.html.erb
<% if admin_signed_in? %>
<div class="sidebar card text-dark bg-light mb-5 shadow-lg sticky-top">
  <div class="card-header text-center">
    <div class="text-dark">
      <div class="row">
        <div class="col-12">管理者ログイン中</div>
      </div>
    </div>
  </div>
  <div class="card-body">
    <ul class="card-text list-unstyled">
      <li><%= link_to '[投稿]新しい順', admin_root_path(sort: 'latest') %></li>
      <li><%= link_to '[投稿]古い順', admin_root_path(sort: 'old') %></li>
      <li>
        <%= link_to admin_root_path(sort: 'star_count') do %>
          [投稿]<i class="fas fa-star"></i>が多い順
        <% end %>
      </li>
      <li><%= link_to '[投稿]いいね多い順', admin_root_path(sort: 'favorite_count') %></li>
      <li><%= link_to '[投稿]コメント多い順', admin_root_path(sort: 'comment_count') %></li>
    </ul>
  </div>
</div>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= obj.errors.count %>件エラーがあります。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-center text-white pt-3">
  <p class="copyright">© 2023 Gourmemo Inc. All Rights Reserved.</p>
  <% if current_page?(root_path) %>
    <div><%= link_to "管理者はこちら", admin_session_path, class: "text-white" %></div>
  <% end %>
</footer>

app/views/layouts/_header.html.erb
<header class="fixed-top">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
      <% if admin_signed_in? %>
        <%= link_to admin_root_path do %>
          <%= image_tag('logo.png') %>
        <% end %>
      <% else %>
        <%= link_to root_path do %>
          <%= image_tag('logo.png') %>
        <% end %>
      <% end %>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Taggle navigaion">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown" style>
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to my_page_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user"></i>マイページ
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_post_path, class: 'nav-link text-light ', 'data-turbolinks': false do %>
                <i class="fas fa-edit"></i>新規投稿
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to posts_path, class: 'nav-link text-light' do %>
                <i class="fas fa-utensils"></i>投稿一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i>ユーザー一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to admin_root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-utensils"></i>投稿一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  admin_users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i>ユーザー一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i>About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to posts_path, class: 'nav-link text-light' do %>
                <i class="fas fa-utensils"></i>投稿一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i>新規登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path , class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i>ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_public_sidebar.html.erb
<% if user_signed_in? %>
  <div class="sidebar card text-dark bg-light mb-5 shadow-lg sticky-top">
    <div class="card-header text-center">
      <div class="text-dark">
        <div class="row">
          <div class="col-12">ログイン中</div>
          <div class="col-12">
            <%= image_tag current_user.get_profile_image(50,50), class: "mt-o rounded-circle"; %>
            <%= current_user.name %>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body">
      <ul class="card-text list-unstyled">
        <li><%= link_to '[投稿]新しい順', posts_path(sort: 'latest') %></li>
        <li><%= link_to '[投稿]古い順', posts_path(sort: 'old') %></li>
        <li>
          <%= link_to posts_path(sort: 'star_count') do %>
            [投稿]<i class="fas fa-star"></i>が多い順
          <% end %>
        </li>
        <li><%= link_to '[投稿]いいね多い順', posts_path(sort: 'favorite_count') %></li>
        <li><%= link_to '[投稿]コメント多い順', posts_path(sort: 'comment_count') %></li>
        <% if current_user.name != "guestuser" %>
          <li>
            <%= link_to confirm_deleted_path do %>
              <font color="#f00">
                <i class="fas fa-exclamation-triangle"></i>
                退会する
              </font>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>グルメモ</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/cc0284726c.js" crossorigin="anonymous"></script>
  </head>

  <body class="<%= @classname %>">
    <div class="wrapper">
      <div class="mb-4">
        <%= render 'layouts/header' %>
      </div>

      <% if flash[:notice] %>
       <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
       </div>
      <% end %>

      <% if flash[:alert] %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:alert] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>

      <% if admin_signed_in? %>
        <div class="text-center my-5">
          <%= render 'admin/searches/form' %>
        </div>
      <% elsif user_signed_in? %>
        <div class="text-center my-5">
          <%= render 'public/searches/form' %>
        </div>
      <% end %>

      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>